// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	CasbinRule     *casbinRule
	CodeIndex      *codeIndex
	Dept           *dept
	LoginLog       *loginLog
	Permission     *permission
	Role           *role
	RolePermission *rolePermission
	Setting        *setting
	User           *user
	UserRole       *userRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	CasbinRule = &Q.CasbinRule
	CodeIndex = &Q.CodeIndex
	Dept = &Q.Dept
	LoginLog = &Q.LoginLog
	Permission = &Q.Permission
	Role = &Q.Role
	RolePermission = &Q.RolePermission
	Setting = &Q.Setting
	User = &Q.User
	UserRole = &Q.UserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		CasbinRule:     newCasbinRule(db, opts...),
		CodeIndex:      newCodeIndex(db, opts...),
		Dept:           newDept(db, opts...),
		LoginLog:       newLoginLog(db, opts...),
		Permission:     newPermission(db, opts...),
		Role:           newRole(db, opts...),
		RolePermission: newRolePermission(db, opts...),
		Setting:        newSetting(db, opts...),
		User:           newUser(db, opts...),
		UserRole:       newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CasbinRule     casbinRule
	CodeIndex      codeIndex
	Dept           dept
	LoginLog       loginLog
	Permission     permission
	Role           role
	RolePermission rolePermission
	Setting        setting
	User           user
	UserRole       userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		CasbinRule:     q.CasbinRule.clone(db),
		CodeIndex:      q.CodeIndex.clone(db),
		Dept:           q.Dept.clone(db),
		LoginLog:       q.LoginLog.clone(db),
		Permission:     q.Permission.clone(db),
		Role:           q.Role.clone(db),
		RolePermission: q.RolePermission.clone(db),
		Setting:        q.Setting.clone(db),
		User:           q.User.clone(db),
		UserRole:       q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		CasbinRule:     q.CasbinRule.replaceDB(db),
		CodeIndex:      q.CodeIndex.replaceDB(db),
		Dept:           q.Dept.replaceDB(db),
		LoginLog:       q.LoginLog.replaceDB(db),
		Permission:     q.Permission.replaceDB(db),
		Role:           q.Role.replaceDB(db),
		RolePermission: q.RolePermission.replaceDB(db),
		Setting:        q.Setting.replaceDB(db),
		User:           q.User.replaceDB(db),
		UserRole:       q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	CasbinRule     ICasbinRuleDo
	CodeIndex      ICodeIndexDo
	Dept           IDeptDo
	LoginLog       ILoginLogDo
	Permission     IPermissionDo
	Role           IRoleDo
	RolePermission IRolePermissionDo
	Setting        ISettingDo
	User           IUserDo
	UserRole       IUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CasbinRule:     q.CasbinRule.WithContext(ctx),
		CodeIndex:      q.CodeIndex.WithContext(ctx),
		Dept:           q.Dept.WithContext(ctx),
		LoginLog:       q.LoginLog.WithContext(ctx),
		Permission:     q.Permission.WithContext(ctx),
		Role:           q.Role.WithContext(ctx),
		RolePermission: q.RolePermission.WithContext(ctx),
		Setting:        q.Setting.WithContext(ctx),
		User:           q.User.WithContext(ctx),
		UserRole:       q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
